PETSC_DIR=/usr/local/Cellar/petsc/3.2p7-debug/
SLEPC_DIR=/usr/local/Cellar/slepc/3.2p5-debug/
TDSEBASE=/Users/spott/Documents/Code/ebss

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
#include ${SLEPC_DIR}/conf/slepc_common

CPP_FLAGS=-I${TDSEBASE}/ -g
LDFLAGS=-lgsl

BINDIR=${TDSEBASE}/bin/

#-L${SLEPC_DIR}/lib/ -lslepc -L${PETSC_DIR}/lib/ -lpetsc
