PETSC_DIR=/home/ansp6066/local/petsc-3.3/
SLEPC_DIR=/home/ansp6066/local/slepc-3.3/
TDSEBASE=/home/ansp6066/code/ebss

#include ${PETSC_DIR}/conf/variables
#include ${PETSC_DIR}/conf/rules
include ${SLEPC_DIR}/conf/slepc_common

CPP_FLAGS=-I${TDSEBASE}/
LDFLAGS=-lgsl

BINDIR=${TDSEBASE}/bin/

#-L${SLEPC_DIR}/lib/ -lslepc -L${PETSC_DIR}/lib/ -lpetsc
